#ifndef _BIG_MAP_TILEMAP_H
#define _BIG_MAP_TILEMAP_H

extern const UINT8 BIG_TILEMAP[];
#define BIG_MAP_TILEMAP_WIDTH 32
#define BIG_MAP_TILEMAP_HEIGHT 32

extern const UINT8 TOO_BIG_TILEMAP[];
#define TOO_BIG_MAP_TILEMAP_WIDTH 33
#define TOO_BIG_MAP_TILEMAP_HEIGHT 32

#endif
