// This file was generated by img2gb, DO NOT EDIT

#ifndef _GAMEBOY_FRONT_TILESET_H
#define _GAMEBOY_FRONT_TILESET_H

extern const UINT8 GAMEBOY_FRONT_TILESET[];
#define GAMEBOY_FRONT_TILESET_TILE_COUNT 97


#endif
